server:
  port: 8088


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/tmall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      username: root
      password: root
      initial-size: 1
      max-active: 6
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    encoding: utf-8
    suffix: .html
    mode: HTML
    cache: false
    check-template-location: true

mybatis:
  type-aliases-package: master.springbootmvc.tmall.model
  mapper-locations: classpath:mapper/.*xml

